//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCooperative.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAnalysis
    {
        public int Id { get; set; }
        public int Id_Patient { get; set; }
        public int Id_Doctor { get; set; }
        public int Id_Diagnosis { get; set; }
        public string Description { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
