//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCooperative.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors()
        {
            this.BookAnalysis = new HashSet<BookAnalysis>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_category { get; set; }
        public string Cabinet { get; set; }
        public int Id_gender { get; set; }
        public int Id_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAnalysis> BookAnalysis { get; set; }
        public virtual Category Category { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Status Status { get; set; }
    }
}
